"""create init migration

Revision ID: 3af4b3ac2286
Revises: 0a4c4534927c
Create Date: 2026-07-13 23:50:25.036487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af4b3ac2286'
down_revision: Union[str, Sequence[str], None] = '0a4c4534927c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_image_url')
    # ### end Alembic commands ###
